### PR TITLE
Add Cocoapods support

### PR DESCRIPTION
**Pull request by streeter**
I added support for Cocoapods, and then adjusted the build a bit. Instead of the script to make a static library in the post-build (which didn't work for me), I only have one target: `PerformanceBezierTests`. This now imports the local pod, which also has a dependency on `JRSwizzle`'s pod.

### CODE REVIEW

**Comment by streeter** [comment]
I ran the tests with this branch, and they all run fine. Though I'd definitely like your comments.

One thing that I'd need to do also, is update the README's [including section](https://github.com/adamwulf/PerformanceBezier#including-in-your-project) to talk about Cocoapods instead. I'm not sure what you have in mind though, so feedback is appreciated.

**Comment by adamwulf** [comment]
the build script requires that Real Framework from https://github.com/kstenerud/iOS-Universal-Framework is installed, otherwise it'll fail. if its installed it'll generate a static framework that can be used anywhere else.

i'm honestly not a cocoa pods user (one of the few left who isn't i think :P) - would the first two commits of this PR add in support for cocoa pod users while keeping the build the same for those who aren't?

And thanks for the contributions!!

**Comment by adamwulf** [comment]
Ok, I've actually adjusted how the framework is built to make it easier. It no longer requires modifications to Xcode as it used to. But this PR won't auto-merge anymore. If you re-do the cocoa pods support w/o the pods directory, that'd be awesome.

Thanks!

**Comment by streeter** [comment]
There you go. I rebased off master. Let me know what you think!

**Comment by adamwulf** [comment]
Ok I finally had a chance to sit down and look through this, sorry for the delay! I think I'm gonna just let folks use your fork if they want cocoa pods support.

After looking at what cocoa pods adds and how its organized, I actually prefer a single .framework target and letting folks import that. It's just a cleaner Xcode project, cleaner dev folder, fewer tools needed, and its something I can maintain.

**Pull request closed without merging**
